version: '3'

services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=rocket_sorter
    volumes:
      - mongodb_data:/data/db

  emqx:
    image: emqx/emqx
    container_name: emqx
    ports:
      - "1883:1883"

volumes:
  mongodb_data:
