version: '3'

services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=rocket_sorter
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: